### ISSUE TITLE
About DreamWaQ

### ISSUE THREAD

**Issue by fan-ziqi** [LucienJi/MetaRobotics#1]
Hello, may I ask if the term 'DreamWaQ' in your code repository refers to 'DreamWaQ: Learning Robust Quadrupedal Locomotion With Implicit Terrain Imaging via Deep Reinforcement Learning'? 

I have been researching this paper recently and would like to ask you some questions. 

My WeChat account is fanziqi614, and I look forward to your reply!

**Comment by kc-ustc** [comment]
Thanks for your sharing,I also have some questions about dreamwaq.Looking forward to discussing with the author.
